# Generated by Django 5.2.6 on 2025-09-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ip", models.CharField(db_index=True, max_length=50)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("packet_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("source_ip", "timestamp")},
            },
        ),
    ]
